### Criar um novo usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "password": "password123"
}

###

### Obter todos os usuários
GET http://localhost:3000/api/users

###

### Atualizar um usuário 
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "name": "John Doe Updated",
    "email": "john.doe.updated@example.com",
    "password": "password123"
}

###

### Deletar um usuário
DELETE http://localhost:3000/api/users/18

###

POST http://localhost:3000/api/send
Content-Type: application/json

{
    "subject": "Teste de envio de email",
    "content": "Teste de envio de email",
    "status": true,
    "senderEmail": "test@example.com",
    "recipientEmail": "test2@example.com"
}


### Obter informações da home
GET http://localhost:3000/api/home?email=test@example.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsImlhdCI6MTczMjYzODc5NiwiZXhwIjoxNzMyNjQyMzk2fQ.d2RydjXYV-BOhGCJ3bHrUfYk0RWnaLWbQWNE2-1f2jo
Content-Type: application/json
